USE [master]
GO

/****** Object:  Database [TCC_STG]    Script Date: 08/03/2021 15:04:58 ******/
CREATE DATABASE [TCC_STG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TCC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TCC.mdf' , SIZE = 139264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TCC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TCC_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TCC_STG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TCC_STG] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TCC_STG] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TCC_STG] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TCC_STG] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TCC_STG] SET ARITHABORT OFF 
GO

ALTER DATABASE [TCC_STG] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TCC_STG] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TCC_STG] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TCC_STG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TCC_STG] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TCC_STG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TCC_STG] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TCC_STG] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TCC_STG] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TCC_STG] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TCC_STG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TCC_STG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TCC_STG] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TCC_STG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TCC_STG] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TCC_STG] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TCC_STG] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TCC_STG] SET RECOVERY FULL 
GO

ALTER DATABASE [TCC_STG] SET  MULTI_USER 
GO

ALTER DATABASE [TCC_STG] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TCC_STG] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TCC_STG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TCC_STG] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TCC_STG] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TCC_STG] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TCC_STG] SET  READ_WRITE 
GO


