USE [master]
GO

/****** Object:  Database [TCC_DWH]    Script Date: 08/03/2021 15:05:56 ******/
CREATE DATABASE [TCC_DWH]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TCC_DWH', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TCC_DWH.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TCC_DWH_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TCC_DWH_log.ldf' , SIZE = 204800KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TCC_DWH].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TCC_DWH] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TCC_DWH] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TCC_DWH] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TCC_DWH] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TCC_DWH] SET ARITHABORT OFF 
GO

ALTER DATABASE [TCC_DWH] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TCC_DWH] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TCC_DWH] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TCC_DWH] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TCC_DWH] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TCC_DWH] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TCC_DWH] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TCC_DWH] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TCC_DWH] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TCC_DWH] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TCC_DWH] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TCC_DWH] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TCC_DWH] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TCC_DWH] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TCC_DWH] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TCC_DWH] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TCC_DWH] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TCC_DWH] SET RECOVERY FULL 
GO

ALTER DATABASE [TCC_DWH] SET  MULTI_USER 
GO

ALTER DATABASE [TCC_DWH] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TCC_DWH] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TCC_DWH] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TCC_DWH] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TCC_DWH] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TCC_DWH] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TCC_DWH] SET  READ_WRITE 
GO


